name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        set tag = $(date +%s)
        docker build . --file Dockerfile --tag cnhefang/pythonwithansible:$(tag) && docker push cnhefang/pythonwithansible:($tag)
